sudo: required
services:
  - docker

before_install:
  - docker build -t stasiu7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stasiu7/react-test npm test -- --coverage

after_success:
  - docker build -t stasiu7/multi-client ./client
  - docker build -t stasiu7/multi-nginx ./nginx
  - docker build -t stasiu7/multi-server ./server
  - docker build -t stasiu7/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push stasiu7/multi-client
  - docker push stasiu7/multi-nginx 
  - docker push stasiu7/multi-server
  - docker push stasiu7/multi-worker
